lib: [
  "_build/install/default/lib/Dbms/META"
  "_build/install/default/lib/Dbms/authors.ml"
  "_build/install/default/lib/Dbms/authors.mli"
  "_build/install/default/lib/Dbms/dbms.a"
  "_build/install/default/lib/Dbms/dbms.cma"
  "_build/install/default/lib/Dbms/dbms.cmi"
  "_build/install/default/lib/Dbms/dbms.cmt"
  "_build/install/default/lib/Dbms/dbms.cmx"
  "_build/install/default/lib/Dbms/dbms.cmxa"
  "_build/install/default/lib/Dbms/dbms.ml"
  "_build/install/default/lib/Dbms/dbms__Authors.cmi"
  "_build/install/default/lib/Dbms/dbms__Authors.cmt"
  "_build/install/default/lib/Dbms/dbms__Authors.cmti"
  "_build/install/default/lib/Dbms/dbms__Authors.cmx"
  "_build/install/default/lib/Dbms/dune-package"
  "_build/install/default/lib/Dbms/opam"
]
libexec: [
  "_build/install/default/lib/Dbms/dbms.cmxs"
]
doc: [
  "_build/install/default/doc/Dbms/README.md"
]
